import { chromium } from "@playwright/test";
import { readFileSync } from "node:fs";
const password = readFileSync(".admin-password", "utf8").trim();
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(`console: ${m.text()}`); });
page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
await page.goto("http://127.0.0.1:4173/");
await page.getByLabel("Workspace password").fill(password);
await page.getByRole("button", { name: "Open workspace" }).click();
await page.getByRole("heading", { name: "What needs doing?" }).waitFor({ timeout: 30000 });
await page.goto("http://127.0.0.1:4173/excel");
await page.getByRole("heading", { name: "Find the problems before delegates do" }).waitFor();
await page.locator('.file-drop input[type="file"]').setInputFiles("/Users/pranay/Downloads/Oakridge MUN 2026 - Allocation Matrix (1).xlsx");
await page.waitForTimeout(15000);
console.log("BODY\n" + await page.locator("body").innerText());
console.log("ERRORS\n" + errors.join("\n"));
await browser.close();
